### PR TITLE
Update portuguese translation

### PR DESCRIPTION
**Pull request by hugok79**
Portuguese(pt_PT) translation

### CODE REVIEW

**Comment by hugok79** [comment]
@sdottaka Portuguese translation for https://winmerge.org/?lang=pt_pt

**Comment by gerundt** [comment]
Thank you!

**Comment by hugok79** [comment]
@gerundt Dankeschön

**Comment by hugok79** [comment]
@gerundt @sdottaka The https://winmerge.org/?lang=pt_pt still does not show my recent translation... this is normal?
Another thing, shouldn't the website recognize my lang code and automatically redirect to pt-PT instead of opening https://winmerge.org/?

**Comment by gerundt** [comment]
@hugok79 At least I found the problem (7118ad3e22050ccf5418e0024a8f0d996a8102e5) that you don't saw the recent translation.

**Comment by hugok79** [comment]
Thanks you!

**Pull request merged**
