### PR TITLE
Create sl_SI.po

### PR DESCRIPTION
**Pull request by JadranR**
Slovenian translation  website

### CODE REVIEW

**Comment by JadranR** [comment]
[sl_SI.zip](https://github.com/WinMerge/website/files/5541333/sl_SI.zip)

Slovenian translation WinMerge webpage.

With respect,
Jadran Rudec

**Comment by gerundt** [comment]
Thank you! Committed with de92b79.

**Comment by JadranR** [comment]
Hi, I send you now updated Sllovenian translation per date 16.11.2020.
Translated string:
The <a href="%s">manual</a> explains how to use WinMerge, and documents its capabilities and limitations.
[sl_SI.zip](https://github.com/WinMerge/website/files/5549908/sl_SI.zip)

With respect,
Jadran Rudec

**Comment by gerundt** [comment]
Should be fixed now! 👍

**Pull request closed without merging**
