### PR TITLE
2 16 42

### PR DESCRIPTION
**Pull request by sdottaka**
This PR accompanies the 2.16.42 release and adds an Architecture column to the download table as shown below, and also adds the architecture to the tooltip of the download button.

image
image

### CODE REVIEW

**Comment by sdottaka** [comment]
I forgot to digitally sign the installer, so I'm going to release 2.16.42.1.
https://github.com/WinMerge/winmerge/issues/2395

**Comment by sdottaka** [comment]
I've released version 2.16.42.1 and updated this PR.

**Comment by gerundt** [comment]
Thank your for the PR. The changes are now online!

**Comment by sdottaka** [comment]
Thank you!

**Pull request merged**
